# Project: Gateboy
# Author: Tyler Tricker
# 
# this makefile is for: 
#      - synthesizing the project code
#      - running testbenches
#      - cleaning the file tree before a checkin

interconnect_src = $(wildcard interconnect\*.sv)
peripherals_src  = $(wildcard peripherals\*.sv)
processor_src    = $(wildcard processor\*.sv)
system_src       = $(wildcard system\*.sv)


#build code
all: 
	echo "TODO - ALL"

synthesize:

#simulate all of the testbenches
test:
	echo "TODO"

#clean the filetree
.PHONY: clean
clean:
	rm -rf simulation
	rm -rf output_files
	rm -rf incremental_db
	rm -rf db
	rm -rf *.dpf


.PHONY: qtools
qtools:
	source  .toolspath


